[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
ilog = "1.0.1"
itertools = "0.13.0"
pathfinding = "4.12.0"
regex = "1.11.1"
rustc-hash = "2.1.0"

[profile.test]
opt-level = 3
overflow-checks=true
debug-info=false
